/*
    Este archivo es parte del proyecto AeatModelos.
    Copyright (c) 2020 Irene Solutions SL
    Autores: Irene Solutions SL.

    Este programa es software libre; usted puede redistribuirlo y/o modificarlo
    bajo los términos establecidos en GNU Affero General Public License versión 3
    tal y como han sido publicados por la Free Software Foundation.

    Este programa se distribuye con la intención de que sea útil, pero SIN
    NIGÚN TIPO DE GARANTÍA.

    Para más detalles consulte la licencia GNU Affero General Public.
    Debe se haber recibido una copia de la misma con el presente programa;
    en caso contrario, consulte http://www.gnu.org/licenses o escriba a la 
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA, 02110-1301 USA, o descargue la licencia en la URL:
        http://www.irenesolutions.com/terms-of-use.pdf
    
    Las interfaces de ususario con código modificado y versiones de los
    objetos contenidos en el presente programa deben mostrar las advertencias
    legaels apropiadas, como se requiere en la secion 5 de la licencia GNU Affero
    General Public.

    Usted puede ser liberado de los requerimiento de la licencia mediante
    la compra de una licencia comercial. La compra de la licencia es
    obligatoria en caso de que vaya a desarrollar actividades comerciales
    con el software AeatModelos sin publicar el código fuente de sus 
    propias aplicaciones.
    Estas actividades incluyen: ofrecer servicios de pago como mediante ASP,
    sirviendo los resultados obtenidos mediante el presente software mediante
    aplicaciones web, o empaquetando AeatModelos con un producto de código
    fuente no público.    
       
    Para más información, por favor contacte a Irene Solutions SL. en la
    dirección: info@irenesolutions.com
 */

using System.Collections.Generic;

namespace AeatModelos.Mod390e2019v100
{

    /// <summary>
    /// Descripciones de campos.
    /// </summary>
    public class Txt
    {

        /// <summary>
        /// Diccionario con las descripciones de campo
        /// según clave (página.numcampo).
        /// </summary>
        public static Dictionary<string, string> Den = new Dictionary<string, string>() {
            {"000.001", "Constante. "},
            {"000.002", "Modelo"},
            {"000.003", "Discriminante"},
            {"000.004", "Ejercicio de devengo (EEEE)"},
            {"000.005", "Período. (PP)"},
            {"000.006", "Tipo y cierre"},
            {"000.007", "Constante"},
            {"000.008", "Reservado para la Administración. Rellenar con blancos"},
            {"000.009", "Versión del Programa (Nota 1)"},
            {"000.010", "Reservado para la Administración. Rellenar con blancos"},
            {"000.011", "NIF Empresa Desarrollo (Nota 1)"},
            {"000.012", "Reservado para la Administración. Rellenar con blancos"},
            {"000.013", "Constante"},
            {"000.014", "Contenido del fichero.  Aquí se debe incluir el contenido de las páginas correspondientes a la declaración según el formato descrito para cada página en este mismo documento"},
            {"000.015", "Constante. </T+ modelo+discriminante+Ejercicio+periodo+Tipo+>"},
            {"000.016", "Fin de Registro. Constante CRLF( Hexadecimal 0D0A, Decimal 1310)"},
            {"001.001", "Inicio del identificador de modelo y página."},
            {"001.002", "Modelo. "},
            {"001.003", "Página."},
            {"001.004", "Fin de identificador de modelo."},
            {"001.005", "Indicador de página complementaria. "},
            {"001.006", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"001.007", "1. Sujeto pasivo - NIF.   "},
            {"001.008", "1. Sujeto pasivo - Apellidos o Razón Social. "},
            {"001.009", "1. Sujeto pasivo - Nombre."},
            {"001.010", "2. Devengo - Ejercicio. "},
            {"001.011", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"001.012", "1. Sujeto pasivo - Registro de devolución mensual."},
            {"001.013", "1. Sujeto pasivo - Regimen especial del grupo de entidades"},
            {"001.014", "1. Sujeto pasivo - Número de grupo"},
            {"001.015", "1. Sujeto pasivo - dominante?"},
            {"001.016", "1. Sujeto pasivo - dependiente?"},
            {"001.017", "1. Sujeto pasivo - Tipo régimen especial aplicable. Art 163 sexies.cinco. Si o No"},
            {"001.018", "1. Sujeto pasivo - NIF entidad dominante "},
            {"001.019", "1. Sujeto pasivo - Concurso acreedores en este ejercicio"},
            {"001.020", "1. Sujeto pasivo - Regimen especial del criterio de caja"},
            {"001.021", "1. Sujeto pasivo - Ha sido destinatario del régimen especial del criterio de caja"},
            {"001.022", "2. Devengo - Sustitutiva?"},
            {"001.023", "2. Devengo - Sustitutiva por rectificación de cuotas?"},
            {"001.024", "2. Devengo - Nº justificante declaración anterior"},
            {"001.025", "3. Datos estadísticos - A - Actividades - Principal"},
            {"001.026", "3. Datos estadísticos - B - Clave - Principal"},
            {"001.027", "3. Datos estadísticos - C -Epígrafe I.A.E. - Principal"},
            {"001.028", "3. Datos estadísticos - A - Actividades - Otras - 1ª"},
            {"001.029", "3. Datos estadísticos - B - Clave - Otras 1ª"},
            {"001.030", "3. Datos estadísticos - C -Epígrafe I.A.E. - Otras 1º"},
            {"001.031", "3. Datos estadísticos - A - Actividades - Otras - 2ª"},
            {"001.032", "3. Datos estadísticos - B - Clave - Otras 2ª"},
            {"001.033", "3. Datos estadísticos - C -Epígrafe I.A.E. - Otras 2º"},
            {"001.034", "3. Datos estadísticos - A - Actividades - Otras - 3ª"},
            {"001.035", "3. Datos estadísticos - B - Clave - Otras 3ª"},
            {"001.036", "3. Datos estadísticos - C -Epígrafe I.A.E. - Otras 3º"},
            {"001.037", "3. Datos estadísticos - A - Actividades - Otras - 4ª"},
            {"001.038", "3. Datos estadísticos - B - Clave - Otras 4ª"},
            {"001.039", "3. Datos estadísticos - C -Epígrafe I.A.E. - Otras 4º"},
            {"001.040", "3. Datos estadísticos - A - Actividades - Otras - 5ª"},
            {"001.041", "3. Datos estadísticos - B - Clave - Otras 5ª"},
            {"001.042", "3. Datos estadísticos - C -Epígrafe I.A.E. - Otras 5º"},
            {"001.043", "3. Datos estadísticos - D - Declaración anual operac. con terceras personas."},
            {"001.044", "3. Datos estadísticos - Declaración conjunta - NIF."},
            {"001.045", "3. Datos estadísticos - Declaración conjunta - Razón social"},
            {"001.046", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - NIF."},
            {"001.047", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Apellidos y Nombre/Razón social"},
            {"001.048", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Calle/Pza./Avda."},
            {"001.049", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Nombre de la vía pública"},
            {"001.050", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Número"},
            {"001.051", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Esc."},
            {"001.052", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Piso"},
            {"001.053", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Prta."},
            {"001.054", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Teléfono"},
            {"001.055", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Municipio"},
            {"001.056", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Provincia"},
            {"001.057", "4. Representante - Personas Físicas/Comunid. Bienes - Represent. - Código Postal"},
            {"001.058", "4. Representante - Personas Jurídicas - Represent. 1 - Nombre y Apellidos"},
            {"001.059", "4. Representante - Personas Jurídicas - Represent. 1 - NIF"},
            {"001.060", "4. Representante - Personas Jurídicas - Represent. 1 - Fecha Poder (DDMMAAAA)"},
            {"001.061", "4. Representante - Personas Jurídicas - Represent. 1 - Notaría"},
            {"001.062", "4. Representante - Personas Jurídicas - Represent. 2 - Nombre y Apellidos"},
            {"001.063", "4. Representante - Personas Jurídicas - Represent. 2 - NIF"},
            {"001.064", "4. Representante - Personas Jurídicas - Represent. 2 - Fecha Poder (DDMMAAAA)"},
            {"001.065", "4. Representante - Personas Jurídicas - Represent. 2 - Notaría"},
            {"001.066", "4. Representante - Personas Jurídicas - Represent. 3 - Nombre y Apellidos"},
            {"001.067", "4. Representante - Personas Jurídicas - Represent. 3 - NIF"},
            {"001.068", "4. Representante - Personas Jurídicas - Represent. 3 - Fecha Poder (DDMMAAAA)"},
            {"001.069", "4. Representante - Personas Jurídicas - Represent. 3 - Notaría"},
            {"001.070", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) Incluye Nº Referencia PADRE s"},
            {"001.071", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) Sello electrónico"},
            {"001.072", "Identificador cliente EEDD. RESERVADO PARA LAS EEDD."},
            {"001.073", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"001.074", "Indentificador de Fin de registro"},
            {"002.001", "Inicio del identificador de modelo y página."},
            {"002.002", "Modelo."},
            {"002.003", "Página."},
            {"002.004", "Fin de identificador de modelo."},
            {"002.005", "Indicador de página complementaria."},
            {"002.006", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. ordin. - Base imponible [01]"},
            {"002.007", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. ordin. - Cuota [02]"},
            {"002.008", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. ordin. - Base imponible [03]"},
            {"002.009", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. ordin. - Cuota [04]"},
            {"002.010", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. ordin. - Base imponible [05]"},
            {"002.011", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. ordin. - Cuota [06]"},
            {"002.012", "5. Operaciones Reg. Gral. - Base imponible y cuota - operaciones intragrupo - Base imponible [500]"},
            {"002.013", "5. Operaciones Reg. Gral. - Base imponible y cuota - operaciones intragrupo - Cuota [501]"},
            {"002.014", "5. Operaciones Reg. Gral. - Base imponible y cuota - operaciones intragrupo - Base imponible [502]"},
            {"002.015", "5. Operaciones Reg. Gral. - Base imponible y cuota - operaciones intragrupo - Cuota [503]"},
            {"002.016", "5. Operaciones Reg. Gral. - Base imponible y cuota - operaciones intragrupo - Base imponible [504]"},
            {"002.017", "5. Operaciones Reg. Gral. - Base imponible y cuota - operaciones intragrupo - Cuota [505]"},
            {"002.018", "5. Operaciones Reg. Gral. - Base imponible y cuota - regimen especial criterio caja - Base imponible [643]"},
            {"002.019", "5. Operaciones Reg. Gral. - Base imponible y cuota - regimen especial criterio caja - Cuota [644]"},
            {"002.020", "5. Operaciones Reg. Gral. - Base imponible y cuota - regimen especial criterio caja - Base imponible [645]"},
            {"002.021", "5. Operaciones Reg. Gral. - Base imponible y cuota - regimen especial criterio caja - Cuota [646]"},
            {"002.022", "5. Operaciones Reg. Gral. - Base imponible y cuota - regimen especial criterio caja - Base imponible [647]"},
            {"002.023", "5. Operaciones Reg. Gral. - Base imponible y cuota - regimen especial criterio caja - Cuota [648]"},
            {"002.024", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. bienes usados - Base imponible [07]"},
            {"002.025", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. bienes usados - Cuota [08]"},
            {"002.026", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. bienes usados - Base imponible [09]"},
            {"002.027", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. bienes usados - Cuota [10]"},
            {"002.028", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. bienes usados - Base imponible [11]"},
            {"002.029", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. bienes usados - Cuota [12]"},
            {"002.030", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. agencias viajes - Base imponible [13]"},
            {"002.031", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Reg. espec. agencias viajes - Cuota [14]"},
            {"002.032", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. bienes - Base imponible [21]"},
            {"002.033", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. bienes - Cuota [22]"},
            {"002.034", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. bienes - Base imponible [23]"},
            {"002.035", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. bienes - Cuota [24]"},
            {"002.036", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. bienes - Base imponible [25]"},
            {"002.037", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. bienes - Cuota [26]"},
            {"002.038", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. servicios - Base Imponible [545]"},
            {"002.039", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. servicios - Cuota [546]"},
            {"002.040", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. servicios - Base Imponible [547]"},
            {"002.041", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. servicios - Cuota [548]"},
            {"002.042", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. servicios - Base Imponible [551]"},
            {"002.043", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Adquis. intracomunit. servicios - Cuota [552]"},
            {"002.044", "5. Operaciones Reg. Gral. - Base Imponible y cuota - IVA deveng. invers. sujeto pasivo - Base imponible [27]"},
            {"002.045", "5. Operaciones Reg. Gral. - Base Imponible y cuota - IVA deveng. invers. sujeto pasivo - Cuota [28]"},
            {"002.046", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modificac. bases y cuotas - Base imponible [29]"},
            {"002.047", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modificac. bases y cuotas - Cuota [30]"},
            {"002.048", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modificac. bases y cuotas intragrupo - Base [649]"},
            {"002.049", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modificac. bases y cuotas intragrupo - Cuota [650]"},
            {"002.050", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modificac. bases/cuotas concurso acreedores - Base imponible [31]"},
            {"002.051", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modificac. bases/cuotas concurso acreedores - Cuota [32]"},
            {"002.052", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Total bases y cuotas IVA - Base imponible [33]"},
            {"002.053", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Total bases y cuotas IVA - Cuota [34]"},
            {"002.054", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Base imponible [35]"},
            {"002.055", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Cuota [36]"},
            {"002.056", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Base imponible [599]"},
            {"002.057", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Cuota [600]"},
            {"002.058", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Base imponible [601]"},
            {"002.059", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Cuota [602]"},
            {"002.060", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Base imponible [41]"},
            {"002.061", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Recargo de equivalencia - Cuota [42]"},
            {"002.062", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modific. recargo equivalencia - Base imponible [43]"},
            {"002.063", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modific. recargo equivalencia - Cuota [44]"},
            {"002.064", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modific. recargo equiv. Concurso acreedores - Base imponible [45]"},
            {"002.065", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Modific. recargo equiv. Concurso acreedores - Cuota [46]"},
            {"002.066", "5. Operaciones Reg. Gral. - Base Imponible y cuota - Total cuotas IVA y recargo equivalencia [47]"},
            {"002.067", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"002.068", "Indentificador de Fin de registro"},
            {"003.001", "Inicio del identificador de modelo y página."},
            {"003.002", "Modelo."},
            {"003.003", "Página."},
            {"003.004", "Fin de identificador de modelo."},
            {"003.005", "Indicador de página complementaria."},
            {"003.006", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. corrientes bienes y servic. - Base imponible [190]"},
            {"003.007", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. corrientes bienes y servic. - Cuota [191]"},
            {"003.008", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. corrientes bienes y servic. - Base imponible [603]"},
            {"003.009", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. corrientes bienes y servic. - Cuota [604]"},
            {"003.010", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. corrientes bienes y servic. - Base imponible [605]"},
            {"003.011", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. corrientes bienes y servic. - Cuota [606]"},
            {"003.012", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. inter. corrientes bienes y servic. - Base imponible [48]"},
            {"003.013", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. inter. corrientes bienes y servic. - Cuota [49]"},
            {"003.014", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intragrupo corrientes - Base imponible [506]"},
            {"003.015", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intragrupo corrientes - Cuota [507]"},
            {"003.016", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intragrupo corrientes - Base imponible [607]"},
            {"003.017", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intragrupo corrientes - Cuota [608]"},
            {"003.018", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intragrupo corrientes - Base imponible [609]"},
            {"003.019", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intragrupo corrientes - Cuota [610]"},
            {"003.020", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. intragrupo corrientes - Base imponible [512]"},
            {"003.021", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. intragrupo corrientes - Cuota [513]"},
            {"003.022", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. bienes de inversion - Base imponible [196]"},
            {"003.023", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. bienes de inversion - Cuota [197]"},
            {"003.024", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. bienes de inversion - Base imponible [611]"},
            {"003.025", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. bienes de inversion - Cuota [612]"},
            {"003.026", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. bienes de inversion - Base imponible [613]"},
            {"003.027", "5. Operaciones Reg. Gral. - IVA deducible - Oper. inter. bienes de inversion - Cuota [614]"},
            {"003.028", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. inter. bienes de inversion - Base imponible [50]"},
            {"003.029", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. inter. bienes de inversion - Cuota [51]"},
            {"003.030", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intra. bienes de inversion - Base imponible [514]"},
            {"003.031", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intra. bienes de inversion - Cuota [515]"},
            {"003.032", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intra. bienes de inversion - Base imponible [615]"},
            {"003.033", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intra. bienes de inversion - Cuota [616]"},
            {"003.034", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intra. bienes de inversion - Base imponible [617]"},
            {"003.035", "5. Operaciones Reg. Gral. - IVA deducible - Oper. intra. bienes de inversion - Cuota [618]"},
            {"003.036", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. intra. bienes de inversion - Base imponible [520]"},
            {"003.037", "5. Operaciones Reg. Gral. - IVA deducible - Total oper. intra. bienes de inversion - Cuota [521]"},
            {"003.038", "5. Operaciones Reg. Gral. - IVA deducible - Import. bienes corrientes - Base imponible [202]"},
            {"003.039", "5. Operaciones Reg. Gral. - IVA deducible - Import. bienes corrientes - Cuota [203]"},
            {"003.040", "5. Operaciones Reg. Gral. - IVA deducible - Import. bienes corrientes - Base imponible [619]"},
            {"003.041", "5. Operaciones Reg. Gral. - IVA deducible - Import. bienes corrientes - Cuota [620]"},
            {"003.042", "5. Operaciones Reg. Gral. - IVA deducible - Import. bienes corrientes - Base imponible [621]"},
            {"003.043", "5. Operaciones Reg. Gral. - IVA deducible - Import. bienes corrientes - Cuota [622]"},
            {"003.044", "5. Operaciones Reg. Gral. - IVA deducible - Total import. bienes corrientes - Base imponible [52]"},
            {"003.045", "5. Operaciones Reg. Gral. - IVA deducible - Total import. bienes corrientes - Cuota [53]"},
            {"003.046", "5. Operaciones Reg. Gral. - IVA deducible - Importacion bienes inversion - Base imponible [208]"},
            {"003.047", "5. Operaciones Reg. Gral. - IVA deducible - Importacion bienes inversion - Cuota [209]"},
            {"003.048", "5. Operaciones Reg. Gral. - IVA deducible - Importacion bienes inversion - Base imponible [623]"},
            {"003.049", "5. Operaciones Reg. Gral. - IVA deducible - Importacion bienes inversion - Cuota [624]"},
            {"003.050", "5. Operaciones Reg. Gral. - IVA deducible - Importacion bienes inversion - Base imponible [625]"},
            {"003.051", "5. Operaciones Reg. Gral. - IVA deducible - Importacion bienes inversion - Cuota [626]"},
            {"003.052", "5. Operaciones Reg. Gral. - IVA deducible - Total importacion bienes inversion - Base imponible [54]"},
            {"003.053", "5. Operaciones Reg. Gral. - IVA deducible - Total importacion bienes inversion - Cuota [55]"},
            {"003.054", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes corrientes - Base imponible [214]"},
            {"003.055", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes corrientes - Cuota [215]"},
            {"003.056", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes corrientes - Base imponible [627]"},
            {"003.057", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes corrientes - Cuota [628]"},
            {"003.058", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes corrientes - Base imponible [629]"},
            {"003.059", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes corrientes - Cuota [630]"},
            {"003.060", "5. Operaciones Reg. Gral. - IVA deducible - Total adqui. intra. bienes corrientes - Base imponible [56]"},
            {"003.061", "5. Operaciones Reg. Gral. - IVA deducible - Total adqui. intra. bienes corrientes - Cuota [57]"},
            {"003.062", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes inversion - Base imponible [220]"},
            {"003.063", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes inversion - Cuota [221]"},
            {"003.064", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes inversion - Base imponible [631]"},
            {"003.065", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes inversion - Cuota [632]"},
            {"003.066", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes inversion - Base imponible [633]"},
            {"003.067", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. bienes inversion - Cuota [634]"},
            {"003.068", "5. Operaciones Reg. Gral. - IVA deducible - Total adqui. intra. bienes inversion - Base imponible [58]"},
            {"003.069", "5. Operaciones Reg. Gral. - IVA deducible - Total adqui. intra. bienes inversion - Cuota [59]"},
            {"003.070", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. servicios - Base imponible [587]"},
            {"003.071", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. servicios - Cuota [588]"},
            {"003.072", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. servicios - Base imponible [635]"},
            {"003.073", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. servicios - Cuota [636]"},
            {"003.074", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. servicios - Base imponible [637]"},
            {"003.075", "5. Operaciones Reg. Gral. - IVA deducible - Adqui. intra. servicios - Cuota [638]"},
            {"003.076", "5. Operaciones Reg. Gral. - IVA deducible - Total adqui. intra. servicios - Base imponible [597]"},
            {"003.077", "5. Operaciones Reg. Gral. - IVA deducible - Total adqui. intra. servicios - Cuota [598]"},
            {"003.078", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"003.079", "Indentificador de Fin de registro"},
            {"004.001", "Inicio del identificador de modelo y página."},
            {"004.002", "Modelo."},
            {"004.003", "Página."},
            {"004.004", "Fin de identificador de modelo."},
            {"004.005", "Indicador de página complementaria."},
            {"004.006", "5. Operaciones Reg. Gral. - IVA deducible - Compensac. rég. especial agric./ganad./pesca - Base impon. [60]"},
            {"004.007", "5. Operaciones Reg. Gral. - IVA deducible - Compensac. rég. especial agric./ganad./pesca - Cuota deduc. [61]"},
            {"004.008", "5. Operaciones Reg. Gral. - IVA deducible - Cuotas deducibles en virtud de resolución administrativa o sentencia firmes con tipos no vigentes - Base impon.  [660]"},
            {"004.009", "5. Operaciones Reg. Gral. - IVA deducible - Cuotas deducibles en virtud de resolución administrativa o sentencia firmes con tipos no vigentes - Cuota deduc. [661]"},
            {"004.010", "5. Operaciones Reg. Gral. - IVA deducible - Rectificación de deducciones - Base imponible [639]"},
            {"004.011", "5. Operaciones Reg. Gral. - IVA deducible - Rectificación de deducciones - Cuota [62]"},
            {"004.012", "5. Operaciones Reg. Gral. - IVA deducible - Rectificación de deducciones intragrupo - Base impon. [651]"},
            {"004.013", "5. Operaciones Reg. Gral. - IVA deducible - Rectificación de deducciones intragrupo - Cuota [652]"},
            {"004.014", "5. Operaciones Reg. Gral. - IVA deducible - Regularización de inversiones [63]"},
            {"004.015", "5. Operaciones Reg. Gral. - IVA deducible - Regularización por aplicación porcentaje definitivo de prorrata [522]"},
            {"004.016", "5. Operaciones Reg. Gral. - IVA deducible - Suma de deducciones [64]"},
            {"004.017", "5. Operaciones Reg. Gral. - Resultado régimen general [65]"},
            {"004.018", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"004.019", "Indentificador de Fin de registro"},
            {"005.001", "Inicio del identificador de modelo y página."},
            {"005.002", "Modelo."},
            {"005.003", "Página."},
            {"005.004", "Fin de identificador de modelo."},
            {"005.005", "Indicador de página complementaria."},
            {"005.006", "6. Operaciones Reg. Simplificado - Actividad 1  - Epígrafe I.A.E. [66]"},
            {"005.007", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 1"},
            {"005.008", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 1"},
            {"005.009", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 2 "},
            {"005.010", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 2"},
            {"005.011", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 3 "},
            {"005.012", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 3"},
            {"005.013", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 4"},
            {"005.014", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 4"},
            {"005.015", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 5"},
            {"005.016", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 5"},
            {"005.017", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 6"},
            {"005.018", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 6"},
            {"005.019", "6. Operaciones Reg. Simplificado - Actividad 1 - A - Nº unidades Módulo 7"},
            {"005.020", "6. Operaciones Reg. Simplificado - Actividad 1 - B - Importe Módulo 7"},
            {"005.021", "6. Operaciones Reg. Simplificado - Actividad 1 - C- Cuota devengada operaciones corrientes "},
            {"005.022", "6. Operaciones Reg. Simplificado - Actividad 1 - Lorca"},
            {"005.023", "6. Operaciones Reg. Simplificado - Actividad 1 - D- Cuota soportadas operaciones corrientes "},
            {"005.024", "6. Operaciones Reg. Simplificado - Actividad 1 - E - Índice corrector"},
            {"005.025", "6. Operaciones Reg. Simplificado - Actividad 1 - F - Resultado "},
            {"005.026", "6. Operaciones Reg. Simplificado - Actividad 1- G - % Cuota mínima"},
            {"005.027", "6. Operaciones Reg. Simplificado - Actividad 1- H - Devolución cuotas soportadas otros países"},
            {"005.028", "6. Operaciones Reg. Simplificado - Actividad 1- I - Cuota mínima"},
            {"005.029", "6. Operaciones Reg. Simplificado - Actividad 1 - Cuota derivada régimen simplificado [J1]"},
            {"005.030", "6. Operaciones Reg. Simplificado - Actividad 2  - Epígrafe I.A.E. [66]"},
            {"005.031", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 1"},
            {"005.032", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 1"},
            {"005.033", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 2"},
            {"005.034", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 2"},
            {"005.035", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 3"},
            {"005.036", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 3"},
            {"005.037", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 4"},
            {"005.038", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 4"},
            {"005.039", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 5"},
            {"005.040", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 5"},
            {"005.041", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 6"},
            {"005.042", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 6"},
            {"005.043", "6. Operaciones Reg. Simplificado - Actividad 2 - A - Nº unidades Módulo 7"},
            {"005.044", "6. Operaciones Reg. Simplificado - Actividad 2 - B - Importe Módulo 7"},
            {"005.045", "6. Operaciones Reg. Simplificado - Actividad 2 - C- Cuota devengada operaciones corrientes "},
            {"005.046", "6. Operaciones Reg. Simplificado - Actividad 2 - Lorca"},
            {"005.047", "6. Operaciones Reg. Simplificado - Actividad 2 - D- Cuota soportadas operaciones corrientes "},
            {"005.048", "6. Operaciones Reg. Simplificado - Actividad 2 - E - Índice corrector"},
            {"005.049", "6. Operaciones Reg. Simplificado - Actividad 2 - F - Resultado "},
            {"005.050", "6. Operaciones Reg. Simplificado - Actividad 2- G - % Cuota mínima"},
            {"005.051", "6. Operaciones Reg. Simplificado - Actividad 2- H - Devolución cuotas soportadas otros países"},
            {"005.052", "6. Operaciones Reg. Simplificado - Actividad 2- I - Cuota mínima"},
            {"005.053", "6. Operaciones Reg. Simplificado - Actividad 2 - Cuota derivada régimen simplificado [J2]"},
            {"005.054", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 1 -  Código  "},
            {"005.055", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 1 - Volumen  ingresos"},
            {"005.056", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 1 - Indice cuota "},
            {"005.057", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 1 - Cuota devengada"},
            {"005.058", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 1 - Cuota soportada"},
            {"005.059", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 1 - Cuota derivada Regimen Simplificado [K1]"},
            {"005.060", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 2 -  Código  "},
            {"005.061", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 2 - Volumen  ingresos"},
            {"005.062", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 2 - Indice cuota "},
            {"005.063", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 2- Cuota devengada"},
            {"005.064", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 2 - Cuota soportada"},
            {"005.065", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 2 - Cuota derivada Regimen Simplificado [K2]"},
            {"005.066", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 3 -  Código  "},
            {"005.067", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 3 - Volumen  ingresos"},
            {"005.068", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 3 - Indice cuota "},
            {"005.069", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 3 - Cuota devengada"},
            {"005.070", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 3 - Cuota soportada"},
            {"005.071", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 3 - Cuota derivada Regimen Simplificado [K3]"},
            {"005.072", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 4-  Código  "},
            {"005.073", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 4- Volumen  ingresos"},
            {"005.074", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 4 - Indice cuota "},
            {"005.075", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 4 - Cuota devengada"},
            {"005.076", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 4 - Cuota soportada"},
            {"005.077", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 4 - Cuota derivada Regimen Simplificado [K4]"},
            {"005.078", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 5-  Código  "},
            {"005.079", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 5 - Volumen  ingresos"},
            {"005.080", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 5 - Indice cuota"},
            {"005.081", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 5 - Cuota devengada"},
            {"005.082", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 5 - Cuota soportada"},
            {"005.083", "6. Operaciones Reg. Simplificado - Act. Agrícolas y Ganaderas - Actividad 5 - Cuota derivada Regimen Simplificado [K5]"},
            {"005.084", "6. Operaciones Reg. Simplificado - IVA devengado - Suma cuotas actividades no agríc., ganad. y forest.  [74]"},
            {"005.085", "6. Operaciones Reg. Simplificado - IVA devengado - Suma cuotas  actividades agríc., ganad. y forest. [75]"},
            {"005.086", "6. Operaciones Reg. Simplificado - IVA devengado en adquisiciones intracomunitarias [76]"},
            {"005.087", "6. Operaciones Reg. Simplificado - IVA devengado - IVA devengado por inversión del sujeto pasivo [77]"},
            {"005.088", "6. Operaciones Reg. Simplificado - IVA devengado - IVA devengado en entregas de activos fijos [78]"},
            {"005.089", "6. Operaciones Reg. Simplificado - IVA devengado - Total cuota resultante [79]"},
            {"005.090", "6. Operaciones Reg. Simplificado - Deducciones - IVA soportado en adquisicion de activos fijos [80]"},
            {"005.091", "6. Operaciones Reg. Simplificado - Deducciones - Regularización de bienes de inversion [81]"},
            {"005.092", "6. Operaciones Reg. Simplificado - Deducciones - Suma de deducciones [82]"},
            {"005.093", "6. Operaciones Reg. Simplificado - Resultado régimen simplificado [83]"},
            {"005.094", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"005.095", "Indentificador de Fin de registro"},
            {"006.001", "Inicio del identificador de modelo y página."},
            {"006.002", "Modelo.. "},
            {"006.003", "Página.  "},
            {"006.004", "Fin de identificador de modelo."},
            {"006.005", "Indicador de página complementaria."},
            {"006.006", "7. Resultado liquidación anual - Regularización cuotas art. 80.Cinco.5ª LIVA [658]"},
            {"006.007", "7. Resultado liquidación anual - Suma de resultados [84]"},
            {"006.008", "7. Resultado liquidación anual - IVA a la importación liquidado por la Aduana (sólo sujetos pasivos con opción de diferimiento) [659]"},
            {"006.009", "7. Resultado liquidación anual - Compensación de cuotas ejercicio anterior [85]"},
            {"006.010", "7. Resultado liquidación anual - Resultado de la liquidación [86]"},
            {"006.011", "8. Tributación razón de territorio - Administraciones - Territorio común [87]  "},
            {"006.012", "8. Tributación razón de territorio - Administraciones - Álava [88] "},
            {"006.013", "8. Tributación razón de territorio - Administraciones - Guipúzcoa [89]"},
            {"006.014", "8. Tributación razón de territorio - Administraciones - Vizcaya [90] "},
            {"006.015", "8. Tributación razón de territorio - Administraciones - Navarra [91] "},
            {"006.016", "8. Tributación razón de territorio - Administraciones - Regularización cuotas art. 80.Cinco.5ª LIVA [658]"},
            {"006.017", "8. Tributación razón de territorio - Administraciones - Suma de resultados [84]"},
            {"006.018", "8. Tributación razón de territorio - Administraciones - Resultado atribuible a territorio común [92]"},
            {"006.019", "8. Tributación razón de territorio - Administraciones - IVA a la importación liquidado por la Aduana(sólo sujetos pasivos con opción de diferimiento) [659]"},
            {"006.020", "8. Tributación razón de territorio - Administraciones - Compens. cuotas ej. anterior atrib. territ. com. [93]"},
            {"006.021", "8. Tributación razón de territorio - Administraciones - Resultado liq. anual atribuible territ. comun [94]"},
            {"006.022", "9. Resultado de las liquidaciones - Total resultados a ingresar autoliquidaciones de IVA del ejercicio [95]"},
            {"006.023", "9. Resultado de las liquidaciones - Total devoluc. mensuales IVA suj. pasivos Regtro. de devolución mensual [96]"},
            {"006.024", "9. Resultado de las liquidaciones - Total devoluc. Por cuotas en la adquisicion de elementos de transporte [524]"},
            {"006.025", "9. Resultado de las liquidaciones - Resultado declaración-liquidación último periodo - A compensar [97]"},
            {"006.026", "9. Resultado de las liquidaciones - Resultado declaración-liquidación último periodo - A devolver [98]"},
            {"006.027", "9. Resultado de las liquidaciones - Cuotas pendientes de compensación generadas en el ejercicio y distintas de las incluidas en la casilla 97 [662]"},
            {"006.028", "9. Resultado de las liquidaciones - Total resultados positivos del ejercicio (modelo 322) [525]"},
            {"006.029", "9. Resultado de las liquidaciones - Total resultados negativos del ejercicio (modelo 322) [526]"},
            {"006.030", "10. Volumen de operaciones - Operaciones en régimen general [99]"},
            {"006.031", "10. Volumen de operaciones - Operaciones régimen especial del criterio de caja [653]"},
            {"006.032", "10. Volumen de operaciones - Entregas intracomunitarias exentas [103]"},
            {"006.033", "10. Volumen de operaciones - Exportaciones y otras operaciones exentas con derecho a deducción [104]"},
            {"006.034", "10. Volumen de operaciones - Operaciones exentas sin derecho a deducción [105]"},
            {"006.035", "10. Volumen de operaciones - Operaciones no sujetas o con inversion de suj. Pasivo [110]"},
            {"006.036", "10. Volumen de operaciones - Entregas de bienes objeto de instalación o montaje en otros Estados miembros [112]"},
            {"006.037", "10. Volumen de operaciones - Operaciones en régimen simplificado [100]"},
            {"006.038", "10. Volumen de operaciones - Operaciones en régimen especias de la agricultura, ganadería y pesca [101]"},
            {"006.039", "10. Volumen de operaciones - Operaciones en régimen especial del recargo de equivalencia [102]."},
            {"006.040", "10. Volumen de operaciones - Operaciones en régimen especias de bienes usados, objetos de arte, antigüedades y objetos de colección [227]."},
            {"006.041", "10. Volumen de operaciones - Operaciones en régimen especial de agencias de viajes [228]."},
            {"006.042", "10. Volumen de operaciones - Entrega de bienes inmuebles y operaciones financieras no habituales [106]"},
            {"006.043", "10. Volumen de operaciones - Entrega de bienes de inversion [107]"},
            {"006.044", "10. Volumen de operaciones - Total volumen de operaciones [108]"},
            {"006.045", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"006.046", "Indentificador de Fin de registro"},
            {"007.001", "Inicio del identificador de modelo y página."},
            {"007.002", "Modelo"},
            {"007.003", "Página"},
            {"007.004", "Fin de identificador de modelo."},
            {"007.005", "Indicador de página complementaria."},
            {"007.006", "11. Oper. Específicas - Adquisiciones interiores exentas [230]"},
            {"007.007", "11. Oper. específicas - Adquisiciones intracomunitarias exentas [109]"},
            {"007.008", "11. Oper. Específicas - Importaciones exentas [231]"},
            {"007.009", "11. Oper. Específicas - Bases imponibles IVA soportado no deducible [232]"},
            {"007.010", "11. Oper. específicas - Oper. sujetas que originan el derecho a la devolución mensual [111]"},
            {"007.011", "11. Oper. específicas - Entrega interior bienes devengada por invers. sujet. pasiv. operac. triangul. [113]"},
            {"007.012", "11. Oper. Específicas - Servicios localizados en el territorio de aplicación del impuesto por inversión del sujeto pasivo [523]"},
            {"007.013", "11. Oper. Específicas - Importes de las entregas de bienes regimen especial criterio caja - Base imponible [654]"},
            {"007.014", "11. Oper. Específicas - Importes de las entregas de bienes regimen especial criterio caja - Cuota [655]"},
            {"007.015", "11. Oper. Específicas - Importes de las adquisiciones de bienes regimen especial criterio caja - Base imponible [656]"},
            {"007.016", "11. Oper. Específicas - Importes de las adquisiciones de bienes regimen especial criterio caja - Cuota [657]"},
            {"007.017", "12. Prorratas - 1 - Actividad desarrollada"},
            {"007.018", "12. Prorratas - 1 - Código CNAE [114]"},
            {"007.019", "12. Prorratas - 1 - Importe de operaciones [115]"},
            {"007.020", "12. Prorratas - 1 - Importe de operaciones con derecho a deducción [116]"},
            {"007.021", "12. Prorratas - 1 - Tipo de prorrata [117]"},
            {"007.022", "12. Prorratas - 1 - % de prorrata [118]"},
            {"007.023", "12. Prorratas - 2 - Actividad desarrollada"},
            {"007.024", "12. Prorratas - 2 - Código CNAE [114]"},
            {"007.025", "12. Prorratas - 2 - Importe de operaciones [115]"},
            {"007.026", "12. Prorratas - 2 - Importe de operaciones con derecho a deducción [116]"},
            {"007.027", "12. Prorratas - 2 - Tipo de prorrata [117]"},
            {"007.028", "12. Prorratas - 2 - % de prorrata [118]"},
            {"007.029", "12. Prorratas - 3 - Actividad desarrollada"},
            {"007.030", "12. Prorratas - 3 - Código CNAE [114]"},
            {"007.031", "12. Prorratas - 3 - Importe de operaciones [115]"},
            {"007.032", "12. Prorratas - 3 - Importe de operaciones con derecho a deducción [116]"},
            {"007.033", "12. Prorratas - 3 - Tipo de prorrata [117]"},
            {"007.034", "12. Prorratas - 3 - % de prorrata [118]"},
            {"007.035", "12. Prorratas - 4 - Actividad desarrollada"},
            {"007.036", "12. Prorratas - 4 - Código CNAE [114]"},
            {"007.037", "12. Prorratas - 4 - Importe de operaciones [115]"},
            {"007.038", "12. Prorratas - 4 - Importe de operaciones con derecho a deducción [116]"},
            {"007.039", "12. Prorratas - 4 - Tipo de prorrata [117]"},
            {"007.040", "12. Prorratas - 4 - % de prorrata [118]"},
            {"007.041", "12. Prorratas - 5 - Actividad desarrollada"},
            {"007.042", "12. Prorratas - 5 - Código CNAE [114]"},
            {"007.043", "12. Prorratas - 5 - Importe de operaciones [115]"},
            {"007.044", "12. Prorratas - 5 - Importe de operaciones con derecho a deducción [116]"},
            {"007.045", "12. Prorratas - 5 - Tipo de prorrata [117]"},
            {"007.046", "12. Prorratas - 5 - % de prorrata [118]"},
            {"007.047", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"007.048", "Indentificador de Fin de registro"},
            {"008.001", "Inicio del identificador de modelo y página."},
            {"008.002", "Modelo"},
            {"008.003", "Página"},
            {"008.004", "Fin de identificador de modelo."},
            {"008.005", "Indicador de página complementaria."},
            {"008.006", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes y servic. - Base imponible [139]"},
            {"008.007", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes y servic. - Cuota deducible [140]"},
            {"008.008", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes inversión - Base imponible [141]"},
            {"008.009", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes inversión - Cuota deducible [142]"},
            {"008.010", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes corrientes - Base imponible [143]"},
            {"008.011", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes corrientes - Cuota deducible [144]"},
            {"008.012", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes inversión - Base imponible [145]"},
            {"008.013", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes inversión - Cuota deducible [146]"},
            {"008.014", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun. - Bienes corrientes - Base imponible [147]"},
            {"008.015", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun.  - Bienes corrientes - Cuota deducible [148]"},
            {"008.016", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun. - Bienes inversión - Base imponible [149]"},
            {"008.017", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun. - Bienes inversión - Cuota deducible [150]"},
            {"008.018", "13. Reg. Deducc. Diferenc.- 1 - Compensac. rég. especial agric./ganad./pesca - Base impon. [151] "},
            {"008.019", "13. Reg. Deducc. Diferenc.- 1 - Compensac. rég. especial agric./ganad./pesca - Cuota deduc. [152] "},
            {"008.020", "13. Reg. Deducc. Diferenc.- 1 - Rectificación de deducciones - Base impon.  [640]"},
            {"008.021", "13. Reg. Deducc. Diferenc.- 1 - Rectificación de deducciones - Cuota deduc. [153]"},
            {"008.022", "13. Reg. Deducc. Diferenc.- 1 - Regularización de inversiones [154]"},
            {"008.023", "13. Reg. Deducc. Diferenc.- 1 - Suma de deducciones [155]"},
            {"008.024", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes y servic. - Base imponible [156]"},
            {"008.025", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes y servic. - Cuota deducible [157]"},
            {"008.026", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes inversión - Base imponible [158]"},
            {"008.027", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes inversión - Cuota deducible [159]"},
            {"008.028", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes corrientes - Base imponible [160]"},
            {"008.029", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes corrientes - Cuota deducible [161]"},
            {"008.030", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes inversión - Base imponible [162]"},
            {"008.031", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes inversión - Cuota deducible [163]"},
            {"008.032", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun. - Bienes corrientes - Base imponible [164]"},
            {"008.033", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun.  - Bienes corrientes - Cuota deducible [165]"},
            {"008.034", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun. - Bienes inversión - Base imponible [166]"},
            {"008.035", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun. - Bienes inversión - Cuota deducible [167]"},
            {"008.036", "13. Reg. Deducc. Diferenc.- 2 - Compensac. rég. especial agric./ganad./pesca - Base impon. [168] "},
            {"008.037", "13. Reg. Deducc. Diferenc.- 2 - Compensac. rég. especial agric./ganad./pesca - Cuota deduc. [169] "},
            {"008.038", "13. Reg. Deducc. Diferenc.- 2 - Rectificación de deducciones - Base impon. [641]"},
            {"008.039", "13. Reg. Deducc. Diferenc.- 2 - Rectificación de deducciones - Cuota decuc. [170]"},
            {"008.040", "13. Reg. Deducc. Diferenc.- 2 - Regularización de inversiones [171]"},
            {"008.041", "13. Reg. Deducc. Diferenc.- 2 - Suma de deducciones [172]"},
            {"008.042", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Operac. Interiores - Bienes y servic. - Base imponible [173]"},
            {"008.043", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Operac. Interiores - Bienes y servic. - Cuota deducible [174]"},
            {"008.044", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Operac. Interiores - Bienes inversión - Base imponible [175]"},
            {"008.045", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Operac. Interiores - Bienes inversión - Cuota deducible [176]"},
            {"008.046", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Importaciones - Bienes corrientes - Base imponible [177]"},
            {"008.047", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Importaciones - Bienes corrientes - Cuota deducible [178]"},
            {"008.048", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Importaciones - Bienes inversión - Base imponible [179]"},
            {"008.049", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Importaciones - Bienes inversión - Cuota deducible [180]"},
            {"008.050", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Adquisic. intracomun. - Bienes corrientes - Base imponible [181]"},
            {"008.051", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Adquisic. intracomun.  - Bienes corrientes - Cuota deducible [182]"},
            {"008.052", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Adquisic. intracomun. - Bienes inversión - Base imponible [183]"},
            {"008.053", "13. Reg. Deducc. Diferenc.- 3 - IVA ded. Adquisic. intracomun. - Bienes inversión - Cuota deducible [184]"},
            {"008.054", "13. Reg. Deducc. Diferenc.- 3 - Compensac. rég. especial agric./ganad./pesca - Base impon. [185] "},
            {"008.055", "13. Reg. Deducc. Diferenc.- 3 - Compensac. rég. especial agric./ganad./pesca - Cuota deduc. [186] "},
            {"008.056", "13. Reg. Deducc. Diferenc.- 3 - Rectificación de deducciones - Base impon. [642]"},
            {"008.057", "13. Reg. Deducc. Diferenc.- 3 - Rectificación de deducciones - Cuota deduc. [187]"},
            {"008.058", "13. Reg. Deducc. Diferenc.- 3 - Regularización de inversiones [188]"},
            {"008.059", "13. Reg. Deducc. Diferenc.- 3 - Suma de deducciones [189]"},
            {"008.060", "RESERVADO PARA LA A.E.A.T. (Dejar en blanco) "},
            {"008.061", "Indentificador de Fin de registro"}

        };

    }
}
