/*
    Este archivo es parte del proyecto AeatModelos.
    Copyright (c) 2018 Irene Solutions SL
    Autores: Irene Solutions SL.

    Este programa es software libre; usted puede redistribuirlo y/o modificarlo
    bajo los términos establecidos en GNU Affero General Public License versión 3
    tal y como han sido publicados por la Free Software Foundation.

    Este programa se distribuye con la intención de que sea útil, pero SIN
    NIGÚN TIPO DE GARANTÍA.

    Para más detalles consulte la licencia GNU Affero General Public.
    Debe se haber recibido una copia de la misma con el presente programa;
    en caso contrario, consulte http://www.gnu.org/licenses o escriba a la 
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA, 02110-1301 USA, o descargue la licencia en la URL:
        http://www.irenesolutions.com/terms-of-use.pdf
    
    Las interfaces de ususario con código modificado y versiones de los
    objetos contenidos en el presente programa deben mostrar las advertencias
    legaels apropiadas, como se requiere en la secion 5 de la licencia GNU Affero
    General Public.

    Usted puede ser liberado de los requerimiento de la licencia mediante
    la compra de una licencia comercial. La compra de la licencia es
    obligatoria en caso de que vaya a desarrollar actividades comerciales
    con el software AeatModelos sin publicar el código fuente de sus 
    propias aplicaciones.
    Estas actividades incluyen: ofrecer servicios de pago como mediante ASP,
    sirviendo los resultados obtenidos mediante el presente software mediante
    aplicaciones web, o empaquetando AeatModelos con un producto de código
    fuente no público.    
       
    Para más información, por favor contacte a Irene Solutions SL. en la
    dirección: info@irenesolutions.com
 */

using System.Collections.Generic;

namespace AeatModelos.Mod303e18v10_20
{

    /// <summary>
    /// Descripciones de campos.
    /// </summary>
    public class Txt
    {

        /// <summary>
        /// Diccionario con las descripciones de campo
        /// según clave (página.numcampo).
        /// </summary>
        public static Dictionary<string, string> Den = new Dictionary<string, string>() {
            {"000.001", "Constante. "},
            {"000.002", "Modelo"},
            {"000.003", "Discriminante"},
            {"000.004", "Ejercicio de devengo (EEEE)"},
            {"000.005", "Período. (PP)"},
            {"000.006", "Tipo y cierre"},
            {"000.007", "Constante"},
            {"000.008", "Reservado para la Administración. Rellenar con blancos"},
            {"000.009", "Versión del Programa (Nota 1)"},
            {"000.010", "Reservado para la Administración. Rellenar con blancos"},
            {"000.011", "NIF Empresa Desarrollo (Nota 1)"},
            {"000.012", "Reservado para la Administración. Rellenar con blancos"},
            {"000.013", "Constante"},
            {"000.014", "Contenido del fichero.  Aquí se debe incluir el contenido de las páginas correspondientes a la declaración según el formato descrito para cada página en este mismo documento"},
            {"000.015", "Constante. </T+ modelo+discriminante+Ejercicio+periodo+Tipo+>"},
            {"000.016", "Fin de Registro. Constante CRLF( Hexadecimal 0D0A, Decimal 1310)"},
            {"001.001", "Inicio del identificador de modelo y página."},
            {"001.002", "Modelo."},
            {"001.003", "Página."},
            {"001.004", "Fin de identificador de modelo. "},
            {"001.005", "Indicador de página complementaria. "},
            {"001.006", "Tipo Declaración"},
            {"001.007", "Identificación (1) - NIF"},
            {"001.008", "Identificación (1) - Apellidos o Razón Social"},
            {"001.009", "Identificación (1) - Nombre"},
            {"001.010", "Devengo (2) - Ejercicio"},
            {"001.011", "Devengo (2) - Período"},
            {"001.012", "Identificación (1) - Inscrito en el Registro de devolución mensual (Art. 30 RIVA)"},
            {"001.013", "Identificación (1) - Tributa exclusivamente en Régimen Simplificado (RS)"},
            {"001.014", "Identificación (1) - Autoliquidación conjunta"},
            {"001.015", "Identificación (1) - Declarado en concurso de acreedores en el presente período de liquidación"},
            {"001.016", "Identificación (1) - Fecha en que se dictó el auto de declaración de concurso"},
            {"001.017", "Identificación (1) - Auto de declaración de concurso dictado en el período"},
            {"001.018", "Identificación (1) - Opción por el régimen especial de criterio de Caja"},
            {"001.019", "Identificación (1) - Destinatario de las operaciones a las que se aplique el régimen especial del criterio de Caja"},
            {"001.020", "Identificación (1) - Opción por la aplicación de la prorrata especial"},
            {"001.021", "Identificación (1) - Revocación de la opción por la aplicación de la prorrata especial"},
            {"001.022", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Base imponible [01]"},
            {"001.023", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Tipo % [02]"},
            {"001.024", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Cuota [03]"},
            {"001.025", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Base imponible [04]"},
            {"001.026", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Tipo % [05]"},
            {"001.027", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Cuota [06]"},
            {"001.028", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Base imponible [07]"},
            {"001.029", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Tipo % [08]"},
            {"001.030", "Liquidación (3) - Regimen General - IVA Devengado - Régimen general - Cuota [09]"},
            {"001.031", "Liquidación (3) - Regimen General - IVA Devengado - Adquisiciones intracomunitarias de bienes y servicios - Base imponible  [10]"},
            {"001.032", "Liquidación (3) - Regimen General - IVA Devengado - Adquisiciones intracomunitarias de bienes y servicios - Cuota [11]"},
            {"001.033", "Liquidación (3) - Regimen General - IVA Devengado - Otras operaciones con inversión del sujeto pasivo (excepto. adq. intracom) - Base imponible  [12]"},
            {"001.034", "Liquidación (3) - Regimen General - IVA Devengado - Otras operaciones con inversión del sujeto pasivo (excepto. adq. intracom) - Cuota [13]"},
            {"001.035", "Liquidación (3) - Regimen General - IVA Devengado - Modificación bases y cuotas- Base imponible  [14]"},
            {"001.036", "Liquidación (3) - Regimen General - IVA Devengado - Modificación bases y cuotas - Cuota [15]"},
            {"001.037", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia- Base imponible [16]"},
            {"001.038", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Tipo % [17]"},
            {"001.039", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Cuota [18]"},
            {"001.040", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Base imponible [19]"},
            {"001.041", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Tipo % [20]"},
            {"001.042", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Cuota [21]"},
            {"001.043", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Base imponible [22]"},
            {"001.044", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Tipo % [23]"},
            {"001.045", "Liquidación (3) - Regimen General - IVA Devengado - Recargo equivalencia - Cuota [24]"},
            {"001.046", "Liquidación (3) - Regimen General - IVA Devengado - Modificaciones bases y cuotas del recargo de equivalencia - Base imponible [25]"},
            {"001.047", "Liquidación (3) - Regimen General - IVA Devengado - Modificaciones bases y cuotas del recargo de equivalencia - Cuota [26]"},
            {"001.048", "Liquidación (3) - Regimen General - IVA Devengado - Total cuota devengada ( [03] + [06] + [09] + [11] + [13] + [15] + [18] + [21] + [24] + [26]) [27]"},
            {"001.049", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en operaciones interiores corrientes - Base [28]"},
            {"001.050", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en operaciones interiores corrientes - Cuota [29]"},
            {"001.051", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en operaciones interiores con bienes de inversión - Base [30] "},
            {"001.052", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en operaciones interiores con bienes de inversión - Cuota [31] "},
            {"001.053", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en las importaciones de bienes corrientes - Base [32]"},
            {"001.054", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en las importaciones de bienes corrientes - Cuota [33]"},
            {"001.055", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en las importaciones de bienes de inversión - Base [34]"},
            {"001.056", "Liquidación (3) - Regimen General - IVA Deducible - Por cuotas soportadas en las importaciones de bienes de inversión - Cuota [35]"},
            {"001.057", "Liquidación (3) - Regimen General - IVA Deducible - En adquisiciones intracomunitarias de bienes y servicios corrientes - Base [36]"},
            {"001.058", "Liquidación (3) - Regimen General - IVA Deducible - En adquisiciones intracomunitarias de bienes y servicios corrientes - Cuota [37]"},
            {"001.059", "Liquidación (3) - Regimen General - IVA Deducible - En adquisiciones intracomunitarias de bienes de inversión - Base [38]"},
            {"001.060", "Liquidación (3) - Regimen General - IVA Deducible - En adquisiciones intracomunitarias de bienes de inversión - Cuota [39]"},
            {"001.061", "Liquidación (3) - Regimen General - IVA Deducible - Rectificación de deducciones - Base [40]"},
            {"001.062", "Liquidación (3) - Regimen General - IVA Deducible - Rectificación de deducciones - Cuota [41]"},
            {"001.063", "Liquidación (3) - Regimen General - IVA Deducible - Compensaciones Régimen Especial A.G. y P. - Cuota [42]"},
            {"001.064", "Liquidación (3) - Regimen General - IVA Deducible - Regularización inversiones - Cuota [43]"},
            {"001.065", "Liquidación (3) - Regimen General - IVA Deducible - Regularización por aplicación del porcentaje definitivo de prorrata - Cuota [44]"},
            {"001.066", "Liquidación (3) - Regimen General - IVA Deducible - Total a deducir ( [29] + [31] + [33] + [35] + [37] + [39] + [41] + [42] + [43] + [44] ) - Cuota [45]"},
            {"001.067", "Liquidación (3) - Regimen General - IVA Deducible - Resultado régimen general ( [27] - [45] ) - Cuota [46]"},
            {"001.068", "Identificación (1) - ¿Existe volumen de operaciones (art. 121 LIVA)?"},
            {"001.069", "Sujeto pasivo que tributa exclusivamente a una Administración tributaria Foral con IVA a la importación liquidado por la Aduana pendiente de ingreso"},
            {"001.070", "¿Ha llevado voluntariamente los Libros registro del IVA a través de la Sede electrónica de la AEAT durante el ejercicio?"},
            {"001.071", "Identificación (1) - ¿Está exonerado de la Declaración-resumen anual del IVA, modelo 390?"},
            {"001.072", "Reservado para la AEAT"},
            {"001.073", "Reservado para la AEAT - Sello electrónico reservado para la AEAT "},
            {"001.074", "Indicador de fin de registro"},
            {"002.001", "Inicio del identificador de modelo y página."},
            {"002.002", "Modelo."},
            {"002.003", "Página."},
            {"002.004", "Fin de identificador de modelo. "},
            {"002.005", "Indicador de página complementaria. Blanco (No complementaria) o 'C' (Complementaria)"},
            {"002.006", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - Código"},
            {"002.007", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - Volumen de ingresos"},
            {"002.008", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - Indice de cuota"},
            {"002.009", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - Cuota devengada"},
            {"002.010", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - 1T/2T/3T - Porcentaje trimestral"},
            {"002.011", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - 1T/2T/3T - Ingreso a cuenta [A]"},
            {"002.012", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - 4T - Cuota soportada"},
            {"002.013", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 1 - 4T  - Cuota anual derivada del regimen simplificado [B]"},
            {"002.014", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - Código"},
            {"002.015", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - Volumen de ingresos"},
            {"002.016", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - Indices de cuota"},
            {"002.017", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - Cuota devengada"},
            {"002.018", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - 1T/2T/3T - Porcentaje trimestral"},
            {"002.019", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - 1T/2T/3T - Ingreso a cuenta [A]"},
            {"002.020", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - 4T - Cuota soportada"},
            {"002.021", "Liquidación (3) - RS - (A) Actividades agrícolas, ganaderas y forestales - Actividad 2 - 4T  - Cuota anual derivada del regimen simplificado [B]"},
            {"002.022", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Epigrafe IAE"},
            {"002.023", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Epigrafe IAE  - Indicador auxiliar de actividad en el caso de epígrafes 691.9 y 722"},
            {"002.024", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 1 - Nº Unidades"},
            {"002.025", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 1 - Importe"},
            {"002.026", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 2 - Nº Unidades"},
            {"002.027", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 2 - Importe"},
            {"002.028", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 3 - Nº Unidades"},
            {"002.029", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 3 - Importe"},
            {"002.030", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 4 - Nº Unidades"},
            {"002.031", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 4 - Importe"},
            {"002.032", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 5 - Nº Unidades"},
            {"002.033", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 5 - Importe"},
            {"002.034", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 6 - Nº Unidades"},
            {"002.035", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 6 - Importe"},
            {"002.036", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 7 - Nº Unidades"},
            {"002.037", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Módulo 7 - Importe"},
            {"002.038", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Cuota devengada operaciones corrientes [C]"},
            {"002.039", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - Reducciones [D]"},
            {"002.040", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 1T/2T/3T - Indice corrector activ. de temporada [Z]"},
            {"002.041", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 1T/2T/3T - Porcentaje ingreso a cuenta [E]"},
            {"002.042", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 1T/2T/3T - Ingreso a cuenta ( ([C] - [D] ) x [E]) [F]"},
            {"002.043", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - Cuotas soportadas operaciones corrientes [G]"},
            {"002.044", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - Índice corrector de actividades de temporada [H]"},
            {"002.045", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - RESULTADO (( [C] - [D] - [G] ) x [H]) [I]"},
            {"002.046", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - Porcentaje cuota mínima [J]"},
            {"002.047", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - Devolución cuotas soportadas otros países [K]"},
            {"002.048", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - Cuota mínima [L]"},
            {"002.049", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 1 - 4T - Cuota anual derivada RS [M]"},
            {"002.050", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Epigrafe IAE"},
            {"002.051", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Epigrafe IAE  - Indicador auxiliar de actividad en el caso de epígrafes 691.9 y 722"},
            {"002.052", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 1 - Nº Unidades"},
            {"002.053", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 1 - Importe"},
            {"002.054", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 2 - Nº Unidades"},
            {"002.055", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 2 - Importe"},
            {"002.056", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 3 - Nº Unidades"},
            {"002.057", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 3 - Importe"},
            {"002.058", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 4 - Nº Unidades"},
            {"002.059", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 4 - Importe"},
            {"002.060", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 5 - Nº Unidades"},
            {"002.061", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 5 - Importe"},
            {"002.062", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 6 - Nº Unidades"},
            {"002.063", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 6 - Importe"},
            {"002.064", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 7 - Nº Unidades"},
            {"002.065", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Módulo 7 - Importe"},
            {"002.066", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Cuota devengada operaciones corrientes [C]"},
            {"002.067", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - Reducciones [D]"},
            {"002.068", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 1T/2T/3T - Indice corrector activ. de temporada [Z]"},
            {"002.069", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 1T/2T/3T - Porcentaje ingreso a cuenta [E]"},
            {"002.070", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 1T/2T/3T - Ingreso a cuenta ( ([C] - [D] ) x [E]) [F]"},
            {"002.071", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - Cuotas soportadas operaciones corrientes [G]"},
            {"002.072", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - Índice corrector de actividades de temporada [H]"},
            {"002.073", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - RESULTADO (( [C] - [D] - [G] ) x [H]) [I]"},
            {"002.074", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - Porcentaje cuota mínima [J]"},
            {"002.075", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - Devolución cuotas soportadas otros países [K]"},
            {"002.076", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - Cuota mínima [L]"},
            {"002.077", "Liquidación (3) - RS - (B) Actividades en RS (exc. a, g y f) - Actividad 2 - 4T - Cuota anual derivada RS [M]"},
            {"002.078", "Liquidación (3) - RS - (B) Actividades en RS - 1T/2T/3T  - Suma de ingresos a cuenta del conjunto de actividades (A1 + A2 + A3 + … + F1 + F2 + F3 + ...) [47]"},
            {"002.079", "Liquidación (3) - RS - (A+B) Actividades en RS - 4T  - Suma de cuotas derivadas RS del conjunto de actividades ( B1 + B2 + ... + M1 + M2 + ... ) [48]"},
            {"002.080", "Liquidación (3) - RS - (A+B) Actividades en RS - 4T  - Suma de ingresos a cuenta realizados en el ejercicio [49]"},
            {"002.081", "Liquidación (3) - RS - (A+B) Actividades en RS - 4T - Resultado ( [48] - [49] ) [50]"},
            {"002.082", "Liquidación (3) - RS - Cuotas devengadas - Adquisiciones intracomunitarias de bienes [51]"},
            {"002.083", "Liquidación (3) - RS - Cuotas devengadas - Entregas de activos fijos [52]"},
            {"002.084", "Liquidación (3) - RS - Cuotas devengadas - IVA devengado por inversión del sujeto pasivo [53]"},
            {"002.085", "Liquidación (3) - RS - Cuotas devengadas - Total cuota resultante Si 1T, 2T, 3T: ( [47] + [51] + [52] + [53] ) [54] Si 4T: ( [50] + [51] + [52] + [53] ) [54]"},
            {"002.086", "Liquidación (3) - RS - IVA deducible - Adquisición o importación de activos fijos [55]"},
            {"002.087", "Liquidación (3) - RS - IVA deducible - Regularización bienes de inversión [56]"},
            {"002.088", "Liquidación (3) - RS - IVA deducible - Total IVA deducible ( [55] + [56] ) [57]"},
            {"002.089", "Liquidación (3) - RS - Resultado RS ( [54] - [57] ) [58]"},
            {"002.090", "Reservado para la AEAT"},
            {"002.091", "Indicador de fin de registro"},
            {"003.001", "Inicio del identificador de modelo y página."},
            {"003.002", "Modelo."},
            {"003.003", "Página."},
            {"003.004", "Fin de identificador de modelo. "},
            {"003.005", "Información adicional - Entregas intracomunitarias de bienes y servicios [59]"},
            {"003.006", "Información adicional - Exportaciones y operaciones asimiladas [60]"},
            {"003.007", "Información adicional - Operaciones no sujetas o con inversión del sujeto pasivo que originan el derecho a deducción [61]"},
            {"003.008", "Información adicional - Exclusivamente para operaciones de entrega de bienes y prestaciones de servicios a las que resulte de aplicación el régimen especial del criterio de Caja. Importes devengados en período de liquidación según art. 75 LIVA. - Base Imponible [62]"},
            {"003.009", "Información adicional - Exclusivamente para operaciones de entrega de bienes y prestaciones de servicios a las que resulte de aplicación el régimen especial del criterio de Caja. Importes devengados en período de liquidación según art. 75 LIVA. - Cuota [63]"},
            {"003.010", "Información adicional - Exclusivamente para operaciones de entrega de bienes y prestaciones de servicios a las que resulte de aplicación el régimen especial del criterio de Caja. Cuotas de IVA soportados en operaciones que tributen por el régimen especial del criterio de caja conforme a la regla general de devengo contenida en el artículo 75 LIVA. - Base Imponible [74]"},
            {"003.011", "Información adicional - Exclusivamente para operaciones de entrega de bienes y prestaciones de servicios a las que resulte de aplicación el régimen especial del criterio de Caja. Cuotas totales de IVA soportados en operaciones que tributen por el régimen especial del criterio de caja conforme a la regla general de devengo contenida en el artículo 75 de LIVA. - Cuota [75]"},
            {"003.012", "Resultado - Regularización cuotas art. 80.cinco.5ª LIVA  [76]"},
            {"003.013", "Resultado - Suma de resultados ( [46] + [58] + [76] ) [64]"},
            {"003.014", "Resultado - % Atribuible a la Administración del Estado [65]"},
            {"003.014B", "Reservado para la AEAT"},
            {"003.015", "Resultado - Atribuible a la Administración del Estado [66]"},
            {"003.016", "Resultado - IVA a la importación liquidado por la Aduana pendiente de ingreso  [77]"},
            {"003.017", "Resultado - Cuotas a compensar de periodos anteriores [67]"},
            {"003.018", "Resultado - Exclusivamente para sujetos pasivos que tributan conjuntamente a la Administración del Estado y a las Diputaciones Forales Resultado de la regularización anual [68]"},
            {"003.019", "Resultado - Resultado ( [66] + [77] - [67] ± [68] ) [69]"},
            {"003.020", "Resultado - A deducir [70]"},
            {"003.021", "Resultado - Resultado de la liquidación ( [69] - [70] ) [71]"},
            {"003.022", "Declaración complementaria"},
            {"003.023", "Número justificante declaración anterior"},
            {"003.024", "Declaración Sin actividad"},
            {"003.025", "Devolución. SWIFT-BIC"},
            {"003.026", "Domiciliación/Devolución - IBAN "},
            {"003.027", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: B - Clave - Principal"},
            {"003.028", "Información adicional - Exclusivamente a cumplimentar en el último periodo  exonerados de la Declaración-resumen anual del IVA: C - Epígrafe IAE - Principal"},
            {"003.029", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: B - Clave - Otras - 1ª"},
            {"003.030", "Información adicional - Exclusivamente a cumplimentar en el último periodo  exonerados de la Declaración-resumen anual del IVA: C - Epígrafe IAE - Otras - 1ª"},
            {"003.031", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: B - Clave - Otras - 2ª"},
            {"003.032", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: C - Epígrafe IAE - Otras - 2ª"},
            {"003.033", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: B - Clave - Otras - 3ª"},
            {"003.034", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: C - Epígrafe IAE - Otras - 3ª"},
            {"003.035", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: B - Clave - Otras - 4ª"},
            {"003.036", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: C - Epígrafe IAE - Otras - 4ª"},
            {"003.037", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: B - Clave - Otras - 5ª"},
            {"003.038", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: C - Epígrafe IAE - Otras - 5ª"},
            {"003.039", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA: D - Marque si ha efectuado operaciones por las que tenga obligación de presentar la declaración anual de operaciones con terceras personas."},
            {"003.040", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones en régimen general [80]"},
            {"003.041", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones en régimen especial del criterio de caja conforme art. 75 LIVA [81]"},
            {"003.042", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Entregas intracomunitarias exentas [93]"},
            {"003.043", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones exentas sin derecho a deducción [83]"},
            {"003.044", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones no sujetas por reglas de localización o con inversión del sujeto pasivo [84]"},
            {"003.045", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Entregas de bienes objeto de instalación o montaje en otros Estados miembros [85]"},
            {"003.046", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones en régimen simplificado [86]"},
            {"003.047", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Entregas de bienes inmuebles no habituales, operaciones financieras y relativas al oro de inversión no habituales [79]"},
            {"003.048", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Total volumen de operaciones ([80]+[81]+[93]+[94]+[83]+[84]+[85]+[86]+[95]+[96]+[97]+[98]-[79]-[99]) [88]"},
            {"003.049", "Reservado para la AEAT"},
            {"003.050", "Información de la tributación por razón de territorio: Álava [89]"},
            {"003.051", "Información de la tributación por razón de territorio: Guipuzcoa [90]"},
            {"003.052", "Información de la tributación por razón de territorio: Vizcaya [91]"},
            {"003.053", "Información de la tributación por razón de territorio: Navarra [92]"},
            {"003.054", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Exportaciones y otras operaciones exentas con derecho a deducción [94]"},
            {"003.055", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones en régimen especial de la agricultura, ganadería y pesca [95]"},
            {"003.056", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones realizadas por sujetos pasivos acogidos al régimen especial del recargo de equivalencia [96]"},
            {"003.057", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones en Régimen especial de bienes usados, objetos de arte, antigüedades y objetos de colección [97]"},
            {"003.058", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Operaciones en régimen especial de Agencias de Viajes [98]"},
            {"003.059", "Información adicional - Exclusivamente a cumplimentar en el último periodo exonerados de la Declaración-resumen anual del IVA - Operaciones realizadas en el ejercicio - Entregas de bienes de inversión [99]"},
            {"003.060", "Información de la tributación por razón de territorio: Territorio común [107]"},
            {"003.061", "Reservado para la AEAT"},
            {"003.062", "Indicador de fin de registro"},
            {"004.001", "Inicio del identificador de modelo y página."},
            {"004.002", "Modelo."},
            {"004.003", "Página."},
            {"004.004", "Fin de identificador de modelo. "},
            {"004.005", "Indicador de página complementaria. Blanco (No complementaria) o 'C' (Complementaria)"},
            {"004.006", "Prorratas - 1 - Código CNAE [500]"},
            {"004.007", "Prorratas - 1 - Importe de operaciones [501]"},
            {"004.008", "Prorratas - 1 - Importe de operaciones con derecho a deducción [502]"},
            {"004.009", "Prorratas - 1 - Tipo de prorrata [503]"},
            {"004.010", "Prorratas - 1 - % de prorrata [504]"},
            {"004.011", "Prorratas - 2 - Código CNAE [505]"},
            {"004.012", "Prorratas - 2 - Importe de operaciones [506]"},
            {"004.013", "Prorratas - 2 - Importe de operaciones con derecho a deducción [507]"},
            {"004.014", "Prorratas - 2 - Tipo de prorrata [508]"},
            {"004.015", "Prorratas - 2 - % de prorrata [509]"},
            {"004.016", "Prorratas - 3 - Código CNAE [510]"},
            {"004.017", "Prorratas - 3 - Importe de operaciones [511]"},
            {"004.018", "Prorratas - 3 - Importe de operaciones con derecho a deducción [512]"},
            {"004.019", "Prorratas - 3 - Tipo de prorrata [513]"},
            {"004.020", "Prorratas - 3 - % de prorrata [514]"},
            {"004.021", "Prorratas - 4 - Código CNAE [515]"},
            {"004.022", "Prorratas - 4 - Importe de operaciones [516]"},
            {"004.023", "Prorratas - 4 - Importe de operaciones con derecho a deducción [517]"},
            {"004.024", "Prorratas - 4 - Tipo de prorrata [518]"},
            {"004.025", "Prorratas - 4 - % de prorrata [519]"},
            {"004.026", "Prorratas - 5 - Código CNAE [520]"},
            {"004.027", "Prorratas - 5 - Importe de operaciones [521]"},
            {"004.028", "Prorratas - 5 - Importe de operaciones con derecho a deducción [522]"},
            {"004.029", "Prorratas - 5 - Tipo de prorrata [523]"},
            {"004.030", "Prorratas - 5 - % de prorrata [524]"},
            {"004.031", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes y servic. - Base imponible [700]"},
            {"004.032", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes y servic. - Cuota deducible [701]"},
            {"004.033", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes inversión - Base imponible [702]"},
            {"004.034", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Operac. Interiores - Bienes inversión - Cuota deducible [703]"},
            {"004.035", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes corrientes - Base imponible [704]"},
            {"004.036", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes corrientes - Cuota deducible [705]"},
            {"004.037", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes inversión - Base imponible [706]"},
            {"004.038", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Importaciones - Bienes inversión - Cuota deducible [707]"},
            {"004.039", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun. - Bienes corrientes - Base imponible [708]"},
            {"004.040", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun.  - Bienes corrientes - Cuota deducible [709]"},
            {"004.041", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun. - Bienes inversión - Base imponible [710]"},
            {"004.042", "13. Reg. Deducc. Diferenc.- 1 - IVA ded. Adquisic. intracomun. - Bienes inversión - Cuota deducible [711]"},
            {"004.043", "13. Reg. Deducc. Diferenc.- 1 - Compensac. rég. especial agric./ganad./pesca - Base impon. [712] "},
            {"004.044", "13. Reg. Deducc. Diferenc.- 1 - Compensac. rég. especial agric./ganad./pesca - Cuota deduc. [713] "},
            {"004.045", "13. Reg. Deducc. Diferenc.- 1 - Rectificación de deducciones - Base impon.  [714]"},
            {"004.046", "13. Reg. Deducc. Diferenc.- 1 - Rectificación de deducciones - Cuota deduc. [715]"},
            {"004.047", "13. Reg. Deducc. Diferenc.- 1 - Regularización de inversiones [716]"},
            {"004.048", "13. Reg. Deducc. Diferenc.- 1 - Suma de deducciones [717]"},
            {"004.049", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes y servic. - Base imponible [718]"},
            {"004.050", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes y servic. - Cuota deducible [719]"},
            {"004.051", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes inversión - Base imponible [720]"},
            {"004.052", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Operac. Interiores - Bienes inversión - Cuota deducible [721]"},
            {"004.053", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes corrientes - Base imponible [722]"},
            {"004.054", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes corrientes - Cuota deducible [723]"},
            {"004.055", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes inversión - Base imponible [724]"},
            {"004.056", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Importaciones - Bienes inversión - Cuota deducible [725]"},
            {"004.057", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun. - Bienes corrientes - Base imponible [726]"},
            {"004.058", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun.  - Bienes corrientes - Cuota deducible [727]"},
            {"004.059", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun. - Bienes inversión - Base imponible [728]"},
            {"004.060", "13. Reg. Deducc. Diferenc.- 2 - IVA ded. Adquisic. intracomun. - Bienes inversión - Cuota deducible [729]"},
            {"004.061", "13. Reg. Deducc. Diferenc.- 2 - Compensac. rég. especial agric./ganad./pesca - Base impon. [730] "},
            {"004.062", "13. Reg. Deducc. Diferenc.- 2 - Compensac. rég. especial agric./ganad./pesca - Cuota deduc. [731] "},
            {"004.063", "13. Reg. Deducc. Diferenc.- 2 - Rectificación de deducciones - Base impon.  [732]"},
            {"004.064", "13. Reg. Deducc. Diferenc.- 2 - Rectificación de deducciones - Cuota deduc. [733]"},
            {"004.065", "13. Reg. Deducc. Diferenc.- 2 - Regularización de inversiones [734]"},
            {"004.066", "13. Reg. Deducc. Diferenc.- 2 - Suma de deducciones [735]"},
            {"004.067", "Reservado para la AEAT"},
            {"004.068", "Indicador de fin de registro"}
        };

    }
}
